/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x10, 0x55, 0xF1, 0x5D, 0x9C, 0xEA, 0x71, 0x48}

/* CONSIDER ADDING AN UNLOCK COMBO. SEE DOCUMENTATION. */
#define VIAL_INSECURE

#define VIAL_TAP_DANCE_ENTRIES 64
#define VIAL_COMBO_ENTRIES 64
#define VIAL_KEY_OVERRIDE_ENTRIES 64
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define TAPPING_TERM 250
#define TAPPING_TOGGLE 3
