/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x1A, 0x2A, 0x38, 0x1B, 0xBB, 0x15, 0xB3, 0x12}

/* CONSIDER ADDING AN UNLOCK COMBO. SEE DOCUMENTATION. */
#define VIAL_INSECURE

#define TAPPING_TERM 250
#define TAPPING_TOGGLE 3
#define DYNAMIC_KEYMAP_LAYER_COUNT  8
#define DYNAMIC_KEYMAP_MACRO_COUNT  64
#define VIAL_TAP_DANCE_ENTRIES      64
#define VIAL_COMBO_ENTRIES          64
#define VIAL_KEY_OVERRIDE_ENTRIES   64
#define VIAL_ALT_REPEAT_KEY_ENTRIES 64
