/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0xC8, 0x74, 0x72, 0x72, 0xEB, 0xA9, 0xA3, 0x6D}

/* CONSIDER ADDING AN UNLOCK COMBO. SEE DOCUMENTATION. */
#define VIAL_INSECURE

#define VIAL_TAP_DANCE_ENTRIES 64
#define VIAL_COMBO_ENTRIES 64
#define VIAL_KEY_OVERRIDE_ENTRIES 64
#define DYNAMIC_KEYMAP_LAYER_COUNT 8
#define TAPPING_TERM 250
#define TAPPING_TOGGLE 3

/* Configure RGB LED indicators*/
#define DISCRETE_CAPS 0
#define DISCRETE_NUML 1
#define DISCRETE_SCRL 2
