/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x62, 0x07, 0xA1, 0x69, 0xE8, 0xB5, 0x54, 0x90}

/* CONSIDER ADDING AN UNLOCK COMBO. SEE DOCUMENTATION. */
#define VIAL_INSECURE

#define TAPPING_TERM 250
#define TAPPING_TOGGLE 3
#define DYNAMIC_KEYMAP_LAYER_COUNT  8
#define DYNAMIC_KEYMAP_MACRO_COUNT  64
#define VIAL_TAP_DANCE_ENTRIES      64
#define VIAL_COMBO_ENTRIES          64
#define VIAL_KEY_OVERRIDE_ENTRIES   64
#define VIAL_ALT_REPEAT_KEY_ENTRIES 64

/* Configure RGB LED indicators*/
#define LAYER_INDICATOR_MIN 5
#define LAYER_INDICATOR_MAX 0
#define ENABLE_PER_KEY_LAYER_INDICATOR
